# Generated by Django 3.1.6 on 2021-02-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
